version: '3.9'

services: 
  kotlinapp: 
    container_name: kotlinapp
    build: # this is the build context: .  
      context: .
      dockerfile: Dockerfile
      args: # these are the arguments that are passed to the dockerfile
        DB_URL: ${DB_URL} 
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    ports: # port exposed to the host machine
      - "8080:8080"
    environment: # these are the environment variables that are passed to the dockerfile
      DB_URL: jdbc:mysql://db:3306/devcode
      DB_USER: root
      DB_PASSWORD: password
    depends_on: # this is the dependency on the db service
      - db
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=devcode
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - kotlin-mysql-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 15s
      retries: 10

volumes:
  kotlin-mysql-db:
    driver: local